### ISSUE TITLE
Cannot show CoT with llava

### ISSUE THREAD

**Issue by mtrazzi** [jam3scampbell/ProctorAI#15]
I get this when I try to show the CoT

```bash
00:00:01 - Traceback (most recent call last):
  File "/Users/a/c/ProctorAI/src/main.py", line 140, in <module>
00:00:01 -     main(model_name=args.model_name, tts=args.tts, cli_mode=args.cli_mode, voice=args.voice, delay_time=args.delay_time, initial_delay=args.initial_delay, countdown_time=args.countdown_time, user_name=args.user_name, print_CoT=args.print_CoT, two_tier=args.two_tier, router_model_name=args.router_model)
  File "/Users/a/c/ProctorAI/src/main.py", line 119, in main
    control_sequence(control_sequence, control_args, router_model, proctor_model, total_cost, user_spec, print_CoT, "user_prompt_strict")
  File "/Users/a/c/ProctorAI/src/main.py", line 82, in control_sequence
    determination, total_cost = model_pipeline(model, judge_model, config[user_prompt_label].format(user_spec=user_spec), total_cost, image_filepaths, print_CoT=print_CoT)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a/c/ProctorAI/src/main.py", line 21, in model_pipeline
    response = model.call_model(user_prompt, system_prompt=config["system_prompt"], image_paths=image_filepaths)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a/c/ProctorAI/src/api_models.py", line 353, in call_model
    response_string = data["message"]["content"]
                      ~~~~^^^^^^^^^^^
KeyError: 'message'
```

Settings:
```bash
{'model': 'claude-3-5-sonnet-20240620', 'tts': False, 'voice': 'Emily', 'cli_mode': False, 'delay_time': 0, 'initial_delay': 0, 'countdown_time': 15, 'user_name': 'Procrastinator', 'print_CoT': True, 'two_tier': True, 'router_model': 'llava'}
```

Is the problem that I'm using llava?

**Comment by mtrazzi** [comment]
ok actuallly I was trying to use llava-llama3 under the hood and it broke at the CoT thing. works with normal llava
